# 阶段 2 实施计划 v2 · 起伏管道 + 地形带 + AI 坡度（**待你审查**）

> 这份是**给你审的实施方案**，不是已完成的工作记录。你可以在任意条目批注「改成…」，
> 我按你的批注修订后再动手。**在你批准之前我不写一行实现代码。**
>
> 上位文档：`docs/plans/tracks-and-elevation.md`（总体计划 v2，已批准）。
> 本文件是其中 §5.1–5.3 + §4 + §7 + §8.2 的落地拆解，加上试玩期间发现的既有缺陷。
>
> **v2 相对 v1 的变化**：按你 2026-09 的批注全面修订。逐条对照见 §0。
> 其中有 **1 条我提出不同做法**（§4.4c 的重力补偿），理由写在那一节，请你裁决。

---

## 〇、你的批注 → 落在哪（便于你核对我没漏）

| 你的批注 | 落在 | 我做了什么 |
|---|---|---|
| 兜底平板必须带碰撞（Layer 1）；可加 `y < plate_top−5` 重置保险 | §4.8 | 写明平板碰撞层 + 新增保险，并标明"视觉穿模但物理站得住"是设计而非 bug |
| 动态障碍的 Y 也要跟随起伏 | §4.2 表 + §5.1 断言 | 核对代码后确认**已经跟随**（`_place_dynamic` 用含 Y 的 `c`），并**新增断言**把它钉住 |
| 物理极限要配刹车距离 `d=(v²−v_t²)/(2a)` | §4.4b2 | 新增"刹车距离前瞻"，`a_brake` 用**实测**值（新增测量步骤） |
| 上坡要补偿重力耗损 | §4.4c | ⚠ **我建议改用"引擎力补偿"而不是直接改 `linear_velocity`**，理由与代价写清了，请你裁决 |
| L4 排队要有超时脱困，防幽灵死锁 | §4.5 步④ | 三重保险：排队超时强制穿插、检查点停留 20s 判 Bug、检查级看门狗（不再"被超时掐断"） |
| 地形带 UV 不能横向拉伸 | §4.7 | 世界米制 UV 公式 + 平板与地形带**同一 tile 尺寸**（20 m）+ UV 密度断言 |
| 物理帧 vs 渲染帧：AI 传感器必须在 `_physics_process` | §4.9 | 新增断言"AI 决策次数 == 物理帧数（±1）"；并纠正"默认 60Hz"→ 本工程 **120Hz** |
| AI 全局超时兜底（检查点停留 >20s 判 Bug 并打印全部状态） | §4.5 步④ | 采纳，打印位置/速度/接地率/当前道路半径 |
| §九 7 个问题的拍板 | §9 | 7 条全部按你的答复写死；只有 §4.4c 那条我提了替代方案 |
| 推荐调用的 Skills | §11 | 逐步映射到 4 个技能 |

---

## 一、这一阶段做完之后，你能看到/摸到什么

| 交付 | 你能感知到的变化 |
|---|---|
| **起伏** | 赛道不再全程贴着 y=0：真实上下坡（温和 4~8 m、坡度 ≤9%；L4 荒漠到 10 m / ≤12%） |
| **地形带** | 路两侧跟着路面起伏的宽地形（含 2 m 路肩），路肩到地形平滑过渡，不悬空、不穿模，纹理**不横向拉伸** |
| **AI 上坡下坡** | 上坡收油 + 引擎力补偿；下坡早刹；**按物理极限 + 刹车距离前瞻**过冰面发夹 |
| **三个新验收** | `--check=elevation`、`--check=elevation-ai`、`--check=assets` 进 `run-all-checks` |
| **三个既有缺陷顺手修掉** | L4 荒漠 AI 卡死（§4.5）、验收自动驾驶在冰面开不完一圈（§4.6）、检查被超时掐断导致**没有结论**（§4.5 步④） |
| **L3 积水视觉** | 下凹弯的积水贴图 + 溅水粒子（**并入阶段 3 的 L3 逐关设计**，因为坑只在那一关存在） |

**这一阶段不做**：五关各自的形态与起伏**数值设计**（阶段 3）。本阶段只在**关卡 1** 上开
一个 4 m 小坡把管道打通，然后撤掉。

---

## 二、贯穿约束（每一步都必须满足）

1. **AGENTS.md 红线**：不硬编码关卡参数（一律 `LevelConfig` + `.tres`）；护栏仍合并为单个
   `StaticBody3D`；小地图仍用 `cull_mask` + 固定相机；墙面摩擦 0.05 + 楔入救援 0.8 m 保留。
2. **生成与验收共用同一份几何逻辑**（`track_layout.gd`）。绝不允许"生成一条路、验收另一条路"。
3. **TDD**：先写检查 → 红 → 实现 → 绿 → 回归 → 提交（附日志摘要）。
4. **排查一律用硬数据**（射线探针 / 物理状态），禁止读代码猜。
5. **不留"改了但没证据"的代码**：没有断言或数字支撑就回退（试玩期间已执行过一次）。
6. **AI 的所有感知与决策只允许在 `_physics_process` 里**（§4.9 有断言钉住），
   否则 240Hz 的机器上 AI 会变强、60Hz 的机器上变傻。

---

## 三、数据结构与配置

### 3.1 高度剖面 DSL

```
elevation_profile := ""                       # 空 = 无起伏（阶段 3 之前是默认值）
elevation_profile := "0:0, 0.22:4.5, 0.45:0.8, 0.70:5.0, 1.0:0"   # t:高度(米)
```

| 规则（违反一律报错并指出第几项） | 理由 |
|---|---|
| `t` 严格递增、∈[0,1]，最后一项必须 `t=1.0` | 否则采样顺序错了，剖面会折返 |
| 首项高度 = 末项高度（都写 0） | 闭环 `Y(0)=Y(L)` |
| 高度 ≥ −3 m（不允许更深的坑） | `plate_top` 按 `min_road_y` 算，太深会让兜底平板离路面太远 |
| 相邻控制点**设计坡度 ≤ 上限的 85%**（L1–L3/L5 ≤7.6%，L4 ≤10.2%） | 三次插值在控制点附近会**过冲**，留余量后实测峰值才压得住上限 |

> ⚠ **t 是归一化位置，不是米 —— 所以坡度无法在解析期判定**（2026-09 拍板，选项 A）。
>
> 相邻坡度 `= Δh / (Δt × L)`，`L` 是**赛道真实长度**，纯文本解析器拿不到。
> 实测教训：任务 1 的第一版把 `Δt` 当成米算，`0.22:4.5` 被判成 **2045% 坡度**（真值是
> 4.5 / (0.22 × 1655.4) ≈ **1.24%**），于是一条**合法**剖面被拒、红了 3 条。
>
> 上表"示例满足 85% 限"这句话**只有在 `L ≥ 约 268 m` 时才成立**
> （4.5 / (0.22 × L) ≤ 0.0765 ⟹ L ≥ 267.4 m）。本项目最短的关卡约 1.3 km，所以
> **该示例在所有关卡上都合规**；但把它当成"与长度无关的规则"就会写出不合规的剖面。
>
> **职责划分（拍板结论）**
> 1. `parse_elevation(text)` = **纯文本与结构校验**：严格递增 / 首项 `t=0` / 末项 `t=1.0` /
>    首尾同高 / `h ≥ −3`，外加**一条与长度无关的量级闸门**
>    （`Δh ≤ 0.85 × grade_limit × Δt × 400 m`，400 m 是"本项目不可能更短"的赛道下限）
>    —— 它只拦明显荒谬的剖面，**不能**代替真实坡度检查。
> 2. **真实坡度判定在 `apply_elevation`（任务 3）**：拿到实测弧长后，
>    在**最终曲线**上按固定弧长采样 + 有限差分量**峰值**（见 §四"关键实现点"最后一条），
>    超限时报错并给出**超限处弧长**。这才是唯一的判定点。
> 3. **阶段 3 设计五关起伏时**：先有赛道长度，再按 `Δh ≤ 0.85 × grade_limit × Δt × L`
>    反推每个控制点的允许高度，别照抄上面的示例数值。


### 3.2 `LevelConfig` 新增字段

```gdscript
@export var elevation_profile := ""     ## 高度剖面 DSL（空 = 平地）
@export var grade_limit := 0.09         ## 坡度硬上限（L4 设 0.12）
@export var min_corner_radius := 15.0   ## 阶段 1 已加
```

五关 `.tres` 在本阶段**全部保持 `elevation_profile = ""`**（除临时给 L1 开坡联调）。

### 3.3 `track_layout.gd` 新增函数（几何逻辑唯一样源）

```gdscript
static func parse_elevation(text: String) -> Dictionary
##   返回 {ok, items:[{t,h}], error}
static func apply_elevation(pts: PackedVector3Array, profile: String,
        grade_limit: float, step: float) -> Dictionary
##   返回 {ok, points, error, max_grade, grade_arc, min_y, max_y}
```

**关键实现点（都来自阶段 1 踩到的真实坑）**

- 高度剖面用独立 `Curve3D`，**必须按 Catmull-Rom 给手柄**（`tangent=(next−prev)/6`）——
  Godot 的 `Curve3D` **没有 `cubic_interp` 属性**，不给手柄时它就是折线（engineering-notes 46/47）。
- **环状鬼点保证接缝 C¹**：首尾各补一个环绕邻点（`(t_{n-1}−1, h_{n-1})` 与 `(1+t_1, h_1)`），
  这样 `Y'(0)` 与 `Y'(L)` 由**同一对邻居**算出 → 相等 → 每圈过线不会被"顶"一下。
- **顺序**：XZ 骨架 → 量 XZ 长度 → 叠高度 → 重建曲线 → 此时 `_road_length` 才是三维弧长。
- **实测坡度在最终曲线上量**（固定弧长采样 + 有限差分），不能在控制点折线上量（阶段 1 的教训）。
  这里也是**坡度唯一的判定点**：`parse_elevation` 拿不到赛道长度 `L`，判不了坡度（见 §3.1 的注）。
- 超限时**报错并给出超限处弧长**。
- ⚠ 任务 3 必须先写一条**坡度超限的红用例**（任务 1 的 10 条只覆盖文本与结构，
  按拍板结论坡度已从解析期移出）：例如 `0:0, 0.05:60.0, 1.0:0` 在 1.6 km 赛道上
  ≈ 72% 坡度，`apply_elevation` 必须拒绝并报出超限弧长。

---

## 四、逐项实现规格

### 4.1 地形带

**决定：`ArrayMesh`（`SurfaceTool` 手写条带），不用 `GridMesh`。**

| 方案 | 代价 | 接缝 |
|---|---|---|
| `GridMesh` | ±120 m × 1.4 km、2 m 站距 → **约 17 万三角面**，网格方向与赛道无关 | 必然错开 |
| **ArrayMesh 横断面** | 2 m 站距 × 每站 10 顶点 → **约 7200 三角面** | 与路面**共用顶点**，数学上无缝 |

**横断面（每站一次，`H = road_width/2`，`y_i` = 该站路面高度）**

| 横向偏移 w | 高度 | 说明 |
|---|---|---|
| `±H`（路面外沿） | `y_i` | **与路面网格完全同一个顶点** → 无缝 |
| `±(H+2.0)` | `y_i − 0.10` | **路肩**：微降排水。护栏在 `H+1.2`，**站在路肩上**（1.2<2.0，护栏底下不是悬崖） |
| `±(H+8.0)` | `y_i − 0.80` | 路缘带 |
| `±(H+30.0)` | `lerp(y_i − 2.5, plate_top, 0.45)` | 缓坡带 |
| `±(H+120.0)` | `plate_top` | 与兜底平板**齐平** → 边缘不悬空、不穿模 |

**不变量（`--check=elevation` 逐点断言）**

1. `terrain_y(w) ≤ y_i − 0.05`（地形永不高过路沿 → 不盖路面、不穿模）
2. `terrain_y(w) ≥ plate_top`（永不掉到平板以下）
3. 外沿 `= plate_top`（不悬空）

**碰撞：地形带不加碰撞**（车到不了——护栏处有 12 m 空气墙），纯视觉 → 零物理开销。
**兜底平板留在 Layer 1 带碰撞**（见 §4.8）。

**共用坐标**：把护栏里"自适应真实弧长走环"抽成 `_walk_ring(want_step)`，护栏与地形带**同源**。

### 4.2 有坡之后必须一起改的地方（**已逐行核对代码**）

| 位置 | 代码实证 | 要做什么 |
|---|---|---|
| 路面网格 | `_build_road` 环点取自 `_sample_at`（含 Y） | ✔ 无需改；确认 `fwd.y = 0` **保留**（不加倾斜） |
| 护栏 / 空气墙 | `_build_guardrails` 环点取自 `_sample_at` | ✔ 无需改 |
| 起终点线 | `_build_start_line` 用 `_sample_at(d)` | ✔ 无需改 |
| 检查点门 | `_build_checkpoints`：`pos + UP*1.5`（相对抬升） | ✔ 无需改 |
| **出生点（玩家）** | `vehicle.gd:334`：`Vector3(target.x, global_position.y, target.z)` ← **Y 用 `main.tscn` 写死的 0.55** | ⚠ **必改** → `target.y + 0.53`（= 0.55 − road_lift，与现状一致但不再写死） |
| 出生点（AI） | `_place_on_grid`：`centerline_point(d) + side*lateral + (0,0.6,0)` | ✔ 无需改 |
| 复位回赛道 | `reset_to_track`：落点 = 中心线点 + `UP*0.8` | ✔ 无需改 |
| 复位回检查点 | `reset_to_checkpoint`：门的世界坐标 + `UP*0.8` | ✔ 无需改 |
| 出界判定 | `_check_out_of_bounds` 用 `Vector2(x,z)` | ✔ 无需改 |
| **静态障碍** | `obstacle_field.gd:125,132`：`Vector3(pos.x, h, pos.z)` ← **Y 写死成 h** | ⚠ **必改** → `Vector3(pos.x, pos.y + h, pos.z)`（碰撞体与视觉都改） |
| **动态障碍** | `_place_dynamic`：`body.position = c + side*center`，`c = centerline_point(arc)` **含 Y**；`_process` 只改 `side` 分量 | ✔ **已经跟随起伏**（你的补充我核对过：不会"平地浮空/上坡陷地"）。新增断言钉住（§5.1） |
| `--check=enclosure` | 起点 = `centerline_point(d) + UP*0.6` | ✔ 无需改 |
| `--check=wallslide`/`obstacles`/`avoid` | 起点取自 `centerline_point` 或护栏 | ✔ 无需改 |
| 相机 | `chase_camera.gd` 全用 `target.global_position` | ✔ 无需改（但**新增"相机不穿地形"断言**，§5.1） |
| 小地图 | 正交俯视 + 全 XZ 2D | ✔ 无需改 |
| **AI** | 转向已忽略 Y；`_lane_point` 含 Y | ⚠ **必改**：见 §4.4 |
| `nearest_on_centerline` | 只用 XZ 距离 | ✔ 阶段 1 已加发夹弯平局裁决 |

### 4.3 新增 `scripts/racing_line.gd`（共享模块，约 150 行）

**为什么必须抽出来**：坡度与限速要被**三处**用到 —— AI 对手、验收自动驾驶、验收打印。
本项目吃过最大的亏就是"两套逻辑各写一份然后漂移"。

```gdscript
static func slope_at(track: Node, arc: float, probe := 8.0) -> float
static func corner_radius_at(track: Node, arc: float, ds := 12.0) -> float
static func speed_limit_kmh(radius: float, a_lat: float, safety := 0.85) -> float
static func lookahead_limit_kmh(track: Node, arc: float, distances: Array,
        a_lat: float, cap_kmh: float) -> float
static func brake_distance(v_kmh: float, v_target_kmh: float, a_brake: float) -> float
```

### 4.4 AI：坡度收油 / 下坡早刹 / 物理极限 + 刹车距离

**（a）坡度感知**（你的批注 3）

- 前视 8 m 取高度差：`grade = (y(arc+8) − y(arc)) / 8`
- `grade > 3%`（上坡）：`limit *= clampf(1 − 4.0·(grade − 0.03), 0.55, 1.0)`（12% 坡 → 收到 64%）
- `grade < −3%`（下坡）：把弯道采样 12/28/48/72 m 乘 `(1 + 0.6·clampf(−grade/0.12, 0, 1))`，
  并把"超速才刹车"的死区从 3.0 m/s 收到 1.5 m/s

**（b）物理极限限速**（不修 L5 必炸）

现状：AI 弯道限速下限 `min_speed_frac = 0.30` → L5 极速 216 km/h，**最低只能降到 65 km/h**；
冰面 `a_lat = 16.0 × 0.5 = 8.0 m/s²`、发夹 `R=18 m`：

```
v_max = sqrt(a_lat · R) = sqrt(8.0 × 18) = 12.0 m/s = 43.2 km/h   （×0.85 → 36.7）
65 > 43.2  →  必然推头出界
```

修法：`setup()` 注入抓地力时同时按倍率缩放 `max_lateral_accel`（保存基准值，避免越乘越小）；
`_target_speed()` 加一条**不受百分比下限约束**的物理限速（两者取小，物理极限不允许被抬回去）。

| 关 | μ | a_lat | 最紧弯 R | 物理限速(×0.85) | 现下限(30%) | 够不够 |
|---|---|---|---|---|---|---|
| L3 雨夜 | 0.7 | 11.2 | 20 | 46 km/h | 54 km/h | 勉强 |
| L4 荒漠 | 0.85 | 13.6 | 60 | 88 km/h | 59 km/h | ✔ |
| **L5 极地** | 0.5 | 8.0 | 18 | **37 km/h** | 65 km/h | ❌ 必须修 |

**（b2）刹车距离前瞻（你的补充）**

只限速不够 —— 还得**提前**减到那个速度：

```
d_need = (v² − v_target²) / (2 · a_brake)
若 到"下一个需要限速的点"的距离 < d_need → 无条件刹车（不看超速死区）
```

`a_brake` **不靠猜**：在 `--check=elevation-ai` 里加一次**实测**（平路 100→0 km/h 全力刹，
量实际减速度），把实测值与抓地力倍率一起注入 AI，并把实测值打进日志便于复核。
例：L5 从 65 → 37 km/h，若实测 `a_brake ≈ 6 m/s²` → `d_need ≈ 18 m`，
也就是说**必须在弯前 18 m 就开始刹**（现在只有 10 m 量级的预判）。

**（c）⚠ 上坡重力补偿 —— 我建议换个做法，请你裁决**

你建议"在物理层面给 `linear_velocity` 动态扣除重力分量"。**我建议不要这么做**：

- 直接改 `linear_velocity` 等于**凭空注入能量**：上坡掉不掉速不再取决于引擎力，而取决于这段代码。
  同一个坡玩家车会掉速、AI 车不掉 → **AI 作弊**，还会污染 `--check=friction`（动力/抓地特性的实测）
  与手感一致性。
- 它还会**掩盖真实问题**：AI 上不去坡时，正确结论是"这关坡度超了 AI 的动力预算"（设计问题），
  而不是把它按平。

**我的替代做法（同样是物理层面，但不是注入能量）**

```
需要额外克服的沿坡重力 = mass · g · sin(θ)
→ 在 AI 的 _update_drive() 里把这一项加到目标引擎力上，允许短时超过 max_engine_force
  （上限 1.35×，相当于"降挡拉高转"，真实车辆也这么做）
→ 若 1.35× 仍维持不住目标速度，就**再降目标速度**（这才是诚实的"上不去"）
```

并把"上坡速度保持率"做成断言：`--check=elevation-ai` 记录上坡段速度保持率（要求 ≥ 平路的 85%），
引擎力触到 1.35× 上限时**打印警告**（提示"这关坡度对 AI 动力预算偏紧"）。

> 若你仍坚持扣 `linear_velocity`：我照做，但请允许我**同时**在日志标注
> "本关 AI 启用了重力补偿（非物理）"，并把 `friction`/`phys` 的结论标注为
> "含 AI 补偿，不代表玩家手感"。

**（d）AI 决策必须在物理帧**（你的补充）

`ai_opponent.gd` 目前只有 `_physics_process`，没有 `_process` ✓。
新增断言（`--check=elevation-ai`）：1 秒内 AI 决策调用次数 == `physics_ticks_per_second`
（**本工程是 120，不是 60**：`project.godot` 里 `physics_ticks_per_second=120`）。
这样任何"把传感器挪到 `_process`"的改动都会被立刻抓住。

### 4.5 ⚠ 顺手修掉：L4 荒漠 AI 卡死（既有缺陷）

**实测证据**（`--check=opponents -Level 3`，L4 荒漠 6 静态 + 2 动态）：
AI 连续自救 **9 次**后被超时掐断，卡死位置固定 `(-271.27, 1.447, 116.81)`、
离中心线 **0.02 m**、`up.y=0.99`（没翻）、**接地 2/4**、速度 **0**、y=1.45 m（骑在石头上）。

**机理**：L4 的动态路障扫掠 1.2~4.4 m → 会扫过 AI 的 2.4 m 车道 → AI 往**中线**闪避 →
静态石头按 `_pick_lateral()` 就摆在**离中线 ≤0.125 m** → 骑上去 → 自救又把它推回石头上。

| 步 | 做法 |
|---|---|
| ① | `clear_lane_for()` 的**触发**只认动态路障（静态障碍按设计不占 AI 车道） |
| ② | **选替代车道**时把**所有**障碍（含静态）都算作占用，并在更长前瞻（horizon×1.5）上检查；候选 = 每个障碍的两侧绕行 + 路两侧极限，取"离当前车道最近且未被占用"的 |
| ③ | 没有任何空车道 → 返回当前车道并置 `_blocked_ahead`，把目标速度压到"能在障碍前停住" → **减速排队** |
| ④ | **防幽灵死锁（你的补充）**：· 在同一障碍前停留 **>5 s** 或速度持续 **0 超过 3 s** → **强制穿插**（把该障碍碰撞体临时禁用 0.5 s 让 AI 通过，并打印诊断）· 单个 AI 在**同一检查点区间停留 >20 s** → 判 Bug，打印**完整物理状态**（位置/速度/接地率/当前道路半径）· **检查级看门狗**：`--check=opponents` 里若 `progress()` 连续 15 s 不增长 → **立刻判失败并退出**（带完整状态），而不是让 `run-check.ps1` 掐进程（掐了就没结论，这次就是这么被坑的） |
| ⑤ | （设计层面，阶段 3）动态路障的扫掠范围不该覆盖 AI 巡航车道 |

> 注：我试过只做 ①，**实测没修好**（仍卡在同一位置），已回退。这次 ①②③④ 一起做，
> 以"L4 上 `opponents` 零自救跑完一圈"为唯一验收。

### 4.6 ⚠ 顺手修掉：验收自动驾驶在冰面上开不完一圈

`main.gd` 里 `--check=lap`/`elevation` 的自动驾驶是另一套瞄准逻辑，**没有物理极限限速**，
L5 冰面发夹（37 km/h 极限）压不住 → 推出界/靠兜底复位 → 检查忽红忽绿。
修法：改用 `racing_line.gd` 的限速（与 AI 同一份），不新增代码路径。

### 4.7 地形带与平板的**纹理平铺**（你的补充：UV 拉伸）

**问题**：地形带从 `H+2` 延伸到 `H+120`，UV 若只按 0~1 写，横向 120 m 会把贴图拉成一团。

**做法（世界米制 UV，不需要 triplanar 也不需要自定义 shader）**

```
u = 横向偏移(米) / TILE
v = 沿赛道弧长(米) / TILE
TILE = 20.0 m
```

每站按**真实米数**写 UV（与路面 `_tri()` 同一套思路，路面 TILE=9 m）。
相邻顶点的 UV 差与它们**实际距离**成正比（线性插值），所以无论横断面顶点多稀疏，
纹理密度都恒定为**每 20 m 一个循环** → 不存在横向拉伸糊成一团。

**与兜底平板的衔接（采纳你的方案）**：平板改用同一个 `TILE=20 m`
（`uv1_scale = size / 20.0`；现在写死 48 ≈ 28 m/循环，与地形带对不上会看到接缝），
并且**平板与地形带同贴图、同 albedo 颜色**，远看接不出缝。

**断言**（进 `--check=assets`）：相邻两站验 `Δu == Δ横向米/TILE`、`Δv == Δ弧长米/TILE`（容差 1e-3），
并验证平板与地形带使用**同一个 TILE 常量**。

### 4.8 兜底平板与"掉出世界"的保险（你的补充 1）

- **平板必须带碰撞**：`StaticBody3D` + `collision_layer = 1`（与路面/护栏同层，车轮射线能打到）。
- 车飞出护栏时的真实行为：**穿过地形带（它没有碰撞）→ 落到平板上站住**；出界判定
  （`_check_out_of_bounds`，按水平偏离）会立刻把车复位回赛道。
  所以"视觉上穿一下地形"是**刻意取舍**（地形带无碰撞换零物理开销），不是 bug —— 文档写清。
- **新增保险**（你的建议）：`vehicle._physics_process` 里
  `if global_position.y < plate_top − 5.0: reset_to_track()`（并打印诊断）。
  它兜住"物理异常导致无限下落"（历史上真出现过：353 km/h 自由落体）。
  Track 暴露 `func plate_top_y() -> float`。

### 4.9 AI 感知的帧率无关性（你的补充）

- 断言：`--check=elevation-ai` 统计 1 秒内 AI 决策次数 == `Engine.physics_ticks_per_second`（±1）
- 代码审查项：`ai_opponent.gd` 不得出现 `_process`（现在没有 ✓）
- 纠正文档口径：本工程物理帧是 **120 Hz**（`project.godot: physics_ticks_per_second=120`），不是 60

---

## 五、三个新验收

### 5.1 `--check=elevation`（快，日常迭代用）

| 断言 | 判据 | 失败时打印 |
|---|---|---|
| 剖面解析 | 严格递增、首尾同高、过冲在限内 | 第几项、期望格式 |
| 全程坡度 | `max\|dy/ds\| ≤ grade_limit` | 超限处**弧长**与该处坡度 |
| 剖面闭环 | `\|Y(0)−Y(L)\| ≤ 0.02 m` 且 `\|Y'(0)−Y'(L)\| ≤ 1%` | 两个数值 |
| **四轮接地（硬指标）** | §5.2 | 打空轮名、车身 y、路面 y、速度、弧长 |
| 地形不变量 | §4.1 三条 | 违反点的弧长与横向偏移 |
| 不穿平板 | `plate_top ≤ min_road_y − 1.0` | 两个数值 |
| **障碍贴合路面** | 所有障碍（含动态，逐秒采样）底面与路面 Y 差 ≤ 0.02 m | 障碍序号/弧长/两个 Y |
| **相机不穿地形** | 相机处 `terrain_height_at()` + 0.3 ≤ 相机 y（用**解析公式**，地形带无碰撞测不了射线） | 相机 y / 地形 y / 弧长 |
| 地形带 UV 密度 | §4.7 的 Δu/Δv 断言 | 实测与期望值 |
| **接缝共用顶点** | 沿中心线每 2 m：路面高度 == 同站地形带的 `y_i` | 首个不等的弧长 |

### 5.2 四轮接地射线规范（你的批注 4）

```gdscript
var q := PhysicsRayQueryParameters3D.create(
        w.global_position,                                   # 轮心（世界坐标）
        w.global_position + Vector3.DOWN * (w.wheel_radius + 0.60),
        1, [car.get_rid()])                                  # mask=1：只打路面/地形
```

- 打空 = 该轮**悬空**，记录 `(弧长, 轮名, 车身 y, 路面 y, 速度)`
- **判据：连续打空 > 0.15 s（120 Hz 下 18 帧）即判失败并退出本项检查**
- 全程接地率 **≥99%**（允许过坡顶那一瞬的正常离地）
- 失败时打印**最严重的 5 处**及附近剖面，直接定位是哪个坡做坏了

### 5.3 `--check=elevation-ai`（慢，合并前跑；你要求拆开）

- AI 独立跑完一圈：零自救、未出界（复用 `opponents` 判定）
- **上坡速度保持率 ≥ 平路的 85%**；引擎力触及 1.35× 上限时打印警告
- **冰面发夹通过性**：弯心速度 ≤ 物理极限 × 1.05，且**刹车起始点**满足 §4.4b2
- **AI 决策次数 == 物理帧数**（§4.9）
- **实测刹车减速度**：平路 100→0 km/h 全力刹，打印实测 `a_brake`（供复核，也注入 AI）
- **看门狗**：`progress()` 连续 15 s 不增长 → 立即失败并打印完整状态

### 5.4 `--check=assets`

| 断言 | 说明 |
|---|---|
| 贴图存在**且已导入**（`.import` 在） | 踩过的坑：拷进来的 PNG 没 `.import` → `ResourceLoader.exists()` 为假 |
| 与 `(关卡索引, weather_type)` 期望表一致 | 荒漠配到雪地 → 直接失败 |
| 运行时 `material_override`：`albedo_texture != null` 且 `albedo_color == WHITE` | 同时挡住"贴图被染成暗绿"的历史 bug |
| 五关 `.tres` 的 `ground_texture` **显式写死** | 推断只作兜底，命中兜底要打警告 |
| 地形带与平板用**同一 TILE** | §4.7 |
| **L3 积水贴图存在且已导入** | 阶段 3 用；本阶段先建断言（该关还没有积水时跳过并打印） |

---

## 六、任务拆解（TDD：先写检查，红 → 实现 → 绿）

> 每步结束都要：`lint` → `parse-check` → 该步验收 → `run-all-checks -Quick` → 提交（附日志摘要）。

| # | 任务 | 先写的检查（红） | 转绿判据 |
|---|---|---|---|
| 1 | `parse_elevation` / `apply_elevation` | `--check=layout` 加 **10 条**剖面用例（合法 4 / 非法 6） | 用例全过；剖面 C¹、坡度不超限 |
| 2 | `racing_line.gd` + 单测 | `--check=layout` 加 **6 条**限速/刹车距离用例（含 L5 冰面 37 km/h、约 18 m 刹车距离） | 用例全过 |
| 3 | 高度叠进曲线 | `--check=elevation` 的"坡度/闭环"两段 | L1 临时 4 m 坡：坡度 ≤9%、`Y(0)=Y(L)`、每 2 m 航向步长仍 ≤8° |
| 4 | 地形带 + 平板（含碰撞、同色同 TILE）+ `_walk_ring` 抽取 | `--check=elevation` 的"地形不变量/不穿平板/接缝/UV 密度"四段 | 全过；`enclosure` 仍 0 缺口 |
| 5 | 出生点 Y（`vehicle.gd:334`）+ 掉出世界保险（§4.8） | 新增"出生点在路面高度 ±0.05" | 出生 y 跟随起跑线高度 |
| 6 | 静态障碍 Y | `--check=obstacles` 加"障碍底面贴合路面" | 全部 `\|y − 路面y\| ≤ 0.02` |
| 7 | AI 坡度 + 物理极限 + **刹车距离前瞻** | `--check=elevation-ai` 的"上坡保持率/冰面通过性" | 保持率 ≥85%、弯心速度 ≤极限×1.05 |
| 8 | 引擎力补偿（§4.4c，按你裁决的做法） | 同上（引擎力上限警告） | 上坡不掉到 85% 以下 |
| 9 | AI 避障四步（§4.5）+ 看门狗 | Runner 增加"关卡 4 的 `opponents`"一行 | **L4 零自救跑完一圈，且不再"被超时掐断"** |
| 10 | 验收自动驾驶改用 `racing_line`（§4.6） | `--check=lap -Level 4` | 稳定跑完、复位 0 |
| 11 | `--check=assets` + 五关显式绑定贴图 | 该检查本身 | 五关贴图全部存在/已导入/配对/未染色/同 TILE |
| 12 | 四轮接地射线（§5.2） | `--check=elevation` 最后一段 | 接地率 ≥99%、无 >0.15 s 连续打空 |
| 13 | 相机不穿地形断言（§5.1） | 同上 | 全程 ≥0.3 m 余量（L4 沙丘上重点看） |
| 14 | 撤掉 L1 临时坡；文档/启动器同步；全量回归 + 推送 | — | `run-all-checks` **20 项全绿**（16 + elevation + elevation-ai + assets + opponents@L4；`opponents` 两行同名不同关卡） |
| **15** | **⚠ 能力缺口（试玩反馈插入）**：AI 弯道限速改走 `racing_line.speed_limit_kmh()`（§4.4b 本已包含，但当时只按"L5 不修必炸"立项）；同时把 `_update_drive` 的 `steer` 0.72 收油与 `_roll_guard_factor` 的方向盘量程对齐玩家车 | 在 `--check=aidiag` 的逐 2.5s 行上加**目标速度 / 物理上限 / 弯道半径**三列（已加，2026-09） | ~~**AI 目标速度 ≥ 该点物理上限 × 0.85 的 80% 的时间占比**~~ → **已被取代**：该口径实测在 L1 上改前改后都是 0%（策略在限速，地面富余一倍），区分不了状态。正式判据改为「策略侧 ≥ 极速×85% / 地面侧 ≥ 物理上限×85%，**取较大者 ≥ 60%**」，见 `docs/testing.md` 的 `aidiag` 行与 `docs/plans/task15-ai-corner-speed.md` 头部 |
| **16** | ✅ **已完成（试玩反馈插入）**：验收自动驾驶的**卡墙自救 + 掉头纠正**。玩家实测"方向相反 + 卡墙"：`--check=lap` 当时**全绿**（只验圈速），而日志里有 5 行 `点积=-1.00`、后轮 `force=-4000`、以 18~23 km/h 倒滑 7 秒；卡墙则因为出界复位要"护栏外 4m"才触发而永远轮不到 | `--check=lap` 新增 ①车头方向 ②卡住 ③**掉头纠正演练**（人为拧 180°）；`--check=aidiag` 新增"玩家车头方向"；`shoot.ps1 -Drive` 新增**行驶中截图** | 三项全绿：掉头纠正 **0.0s**、卡住 0 次、朝后 0 帧；截图 `shots/drive-l1-autopilot.png` 显示车在路面内、夹角 0.1° |

---

## 七、回归矩阵

**快速集（日常迭代，`-Quick`）**：`enclosure` · `wallslide` · `minimap` · `obstacles` ·
`aistart` · `avoid` · `pause` · `flip` · `layout` · `weather` · `friction` · `phys` · `elevation` · `assets`

**合并前全量**：快速集 + `stress` · `opponents`（关卡 4 与 5）· `lap` · `elevation-ai`

> 按你的要求拆开：`elevation`（快，约 25 s）日常跑；`elevation-ai`（约 90 s）只在合并前跑。
> `docs/testing.md` 与 `-Quick` 的说明都会写明这个分工。

---

## 八、风险与回退

| 风险 | 应对 |
|---|---|
| 坡 + 发夹 + 窄路叠加 → AI 上不去 / 车被坡顶弹飞 | 先只在 L1 开 4 m 坡打通；每加一关立刻跑 `elevation`+`lap`+`elevation-ai` |
| 三次插值过冲把坡度顶到上限外 | 设计坡度只用上限 85%；检查采**实测峰值**，超限即红并指出弧长 |
| **地形带 UV 横向拉伸**（你提的隐蔽坑） | 世界米制 UV（§4.7）+ 平板同 TILE + UV 密度断言 |
| **物理帧 vs 渲染帧导致 AI 随帧率变强变傻**（你提的） | AI 只在 `_physics_process`；断言"决策次数==物理帧数"（本工程 120Hz） |
| **AI 幽灵死锁把回归拖垮**（你提的） | 排队超时强制穿插 + 检查点停留 20s 判 Bug + 检查级看门狗（不再被掐进程） |
| 车飞出护栏落到地板上"视觉穿模" | 地形带无碰撞是**刻意取舍**；平板带碰撞站得住；出界判定立刻复位；保险 §4.8 |
| L3 下凹弯把路面埋进平板 | `plate_top` 按 `min_road_y` 算，不写死 0；断言 `plate_top ≤ min_road_y − 1.0` |
| 相机在沙丘上穿地形 | §5.1 相机断言（用解析地形高度，不靠射线） |
| 改动引入"改了没证据"的行为变化 | 每步必须有断言或数字；没有就回退（已执行过一次） |

**回退方式**：每一步一个提交；转不了绿就 `git revert`，并在 `docs/testing.md` 的
「已知缺陷」里如实记一条（含实测数据）。

---

## 九、你的 7 个拍板（已按答复写死）

| # | 你的答复 | 落地位置 |
|---|---|---|
| 1 | 地形带 ±120 m **够**；平板颜色调成和地形带一样 | §4.1 / §4.7（同贴图同 TILE 同 albedo） |
| 2 | L3 下凹 −2.0 m **可以**，但要**积水贴图 + 溅水粒子** | §一 交付表 + §5.4 断言 + **阶段 3 的 L3 设计任务**（坑只在那一关存在；素材仍走 Agnes 开发期生成、打包进游戏） |
| 3 | L4 10 m / 硬限 12% **确认**；注意沙丘上相机跟随 | §5.1 相机断言 + §六 任务 13 |
| 4 | `elevation` 与 `elevation-ai` **拆开** | §5.1 / §5.3 / §七 |
| 5 | `opponents` 加 L4 那一行 **同意**（原则问题） | §六 任务 9 / §七 |
| 6 | 没空车道时**减速排队**接受，配合超时机制 | §4.5 步③④ |
| 7 | **必须修**验收自动驾驶 | §4.6 / §六 任务 10 |

**只剩 1 个待你裁决**：§4.4c 的**上坡重力补偿** —— 我建议"引擎力补偿（≤1.35×）+ 保持率断言"，
而不是直接扣 `linear_velocity`（那等于给 AI 注入能量、坡上作弊，并污染 `friction`/`phys` 的实测结论）。
若你坚持原方案，我照做，但会在日志与验收结论里标注"含 AI 补偿"。

---

## 十、明确不做（YAGNI）

- 五关各自的形态/起伏**数值设计**（阶段 3；L2 的角度序列还要用 `tools/layout_closure.py` 重做）
- 路面倾斜（banking）—— 你已拍板不做
- 小地图坡道明暗、HUD 名次、音效、更多障碍种类
- 运行时 AI 生图（Agnes 素材仍是开发期产物）
- 删除 `ellipse` 段与旧椭圆字段（阶段 3 迁移完才删）

---

## 十一、本阶段调用的 Skills（按你的建议）

| 技能 | 用在哪 |
|---|---|
| `systematic-debugging` | L4 AI 卡死（§4.5）、地形带穿模/接缝排查 —— 结论必须有射线探针或物理日志支撑 |
| `test-driven-development` | 任务 1 的 10 条剖面用例、任务 2 的 6 条限速/刹车用例：先写、跑出红、再实现 |
| `verification-before-completion` | 每步提交前对比"红/绿"终端日志，确认不是假绿（阶段 1 已吃过一次"解析用例 0 个全过"的假绿） |
| `ui-ux-pro-max` | L3 积水视觉（贴图/粒子）、地形带纹理平铺的美学与可读性评估 |
